sudo: required

services:
  - docker

before_install:
  - docker build -t galklein/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true galklein/docker-react npm run test -- --coverage
